In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [8]:
x = [1, 2, 3]
y = [4, 5, 6]

z = [ ]
for i in range(len(x)):
  z.append(x[i] + y[i])

z

[5, 7, 9]

In [9]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [10]:
x = np.arange(1,4)
x

array([1, 2, 3])

In [11]:
type(x)

numpy.ndarray

In [12]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = x + y
z

array([5, 7, 9])

In [13]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = x * y
z

array([ 4, 10, 18])

In [14]:
x = np.arange(1, 4)
y = 3 * x
y

array([3, 6, 9])

In [16]:
x_lists = list(range(1, 1_000_001))
x_numpy = np.arange(1, 1_000_001)

In [17]:
%timeit [2 * comp for comp in x_lists]

72.6 ms ± 15.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit 2 * x_numpy

1.27 ms ± 50.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
x = np.arange(1, 5)
y = x ** 2
y

array([ 1,  4,  9, 16])

In [21]:
x = np.array([1, 10, 100, 1000, 10_000, 100_000])
y = np.log10(x)
y

array([0., 1., 2., 3., 4., 5.])

In [22]:
x = np.array([1, np.e, np.e ** 2, np.e ** 3])
y = np.log(x)
y

array([0., 1., 2., 3.])

In [23]:
x = np.array([1, 2, 3])
c = 5
y = x + c
y

array([6, 7, 8])

In [24]:
x = np.array([-1, 0, 1, 2])
y = 5 * x - 2
y

array([-7, -2,  3,  8])

In [28]:
x = np.arange(1, 5)
y = np.arange(-4, -8, -1,)
x @ y

np.int64(-60)

In [30]:
x.T

array([1, 2, 3, 4])

In [29]:
np.dot(x, y)

np.int64(-60)

In [31]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [32]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [33]:
fives = np.ones(5) * 5
fives

array([5., 5., 5., 5., 5.])

In [34]:
x = np.array([1, 2, 3])
np.linalg.norm(x)

np.float64(3.7416573867739413)

In [35]:
x = np.array([1, 2, 3])
np.linalg.norm(x, ord=1)

np.float64(6.0)

In [39]:
x = np.array([1, 2, 3, 4])
x.shape

(4,)

In [37]:
x.ndim

1