In [66]:
import numpy as np

In [67]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [69]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
3 * M

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [70]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
c = A * B
C

array([[ 6,  8],
       [10, 12]])

In [71]:
A = np.array([
    [-1, 2],
    [-3, -4]
])
np.abs(A)

array([[1, 2],
       [3, 4]])

In [72]:
A = np.array([
    [1, np.sqrt(2)],
    [np.sqrt(3), 2]

])
B = A ** 2
B

array([[1., 2.],
       [3., 4.]])

In [73]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
M.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
np.transpose(M)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
M.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
M.shape
M.ndim

2

In [77]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [78]:
x = np.array([[1, 2, 3]])
x.shape

(1, 3)

In [79]:
x = np.array([
    [1],
    [2],
    [3]
])
x.shape
x

array([[1],
       [2],
       [3]])

In [80]:
x = np.array([1, 2, 3])
x = x.reshape(1, 3)
x

array([[1, 2, 3]])

In [81]:
x = np.array([1, 2, 3])
x = x.reshape(3, 1)
x.shape

(3, 1)

In [82]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [6, 7],
    [8, 9],
    [10, 11]
])
C =  A @ B
C

array([[ 52,  58],
       [124, 139]])

In [83]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
x = np.array([6, 7, 8])
C = A @ x
C

array([ 44, 107, 170])

In [84]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
x = np.array([6, 7, 8])
C = x @ A
C

array([ 90, 111, 132])

In [85]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x @ y

np.int64(32)

In [86]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.outer(x, y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [87]:
x.reshape(3, 1) @ y.reshape(1, 3)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [88]:
M = np.zeros((2, 4))
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
M = np.ones((3, 2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [90]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
D = np.diag([1, 2, 3, 4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [92]:
M = np.array([
    [1, 3, 0],
    [4, 2, 5],
    [9, 8, 7]
])
M[1][2]

np.int64(5)

In [93]:
M = np.array([
    [1, 3, 0],
    [4, 2, 5],
    [9, 8, 7]
])
M[1, 2]

np.int64(5)

In [94]:
M = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
])
M[2]

array([5, 6])

In [95]:
M[2, :]

array([5, 6])

In [96]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 5, 7]
])
M[:, 1]

array([2, 5, 5])

In [97]:
M = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
M[1:3, 2:4]

array([[ 7,  8],
       [11, 12]])

In [98]:
M = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
np.linalg.matrix_rank(M)

np.int64(2)

In [99]:
M = np.array([
    [1, 2, -1],
    [0, 1, -1],
    [1, 0, 2]
])
np.linalg.det(M)

np.float64(1.0)

In [100]:
M = np.array([
    [3, -4],
    [4, 3]
])
np.linalg.inv(M)

array([[ 0.12,  0.16],
       [-0.16,  0.12]])

In [101]:
M = np.array([
    [1, 2, 3],
     [3, 6, 9]
])
np.linalg.pinv(M)

array([[0.00714286, 0.02142857],
       [0.01428571, 0.04285714],
       [0.02142857, 0.06428571]])

In [104]:
A = np.array([
    [2, 3, -4],
    [1, 1, -1],
    [2, 1, 1]
])
b = np.array([-4, 0, 7])
theta = np.linalg.solve(A, b)
theta

array([1., 2., 3.])

In [105]:
A = np.array([
    [2, 3, -4],
    [1, 1, -1],
    [2, 2, -2]
])
b = np.array([-4, 0, 0.1])

theta = np.linalg.lstsq(A, b)[0]
theta

array([2.07333333, 0.01333333, 2.04666667])

In [106]:
A @ theta

array([-4.  ,  0.04,  0.08])

In [124]:
M = np.array([
    [1, 0, -3],
    [0, 5, 2],
    [-3, 2, 8]
])
eigval, eigvec = np.linalg.eigh(M)

print("Eigenvalues:\n", eigval)
print("Eigenvectors:\n", eigvec)

Eigenvalues:
 [-0.20942046  4.36588492  9.84353554]
Eigenvectors:
 [[ 0.91805853  0.26010485 -0.2991889 ]
 [-0.14209114  0.92042494  0.36418131]
 [ 0.37010626 -0.29182767  0.88196257]]


In [125]:
for i in range(len(eigval)):
    left = M @ eigvec[:, i]         # M v
    right = eigval[i] * eigvec[:, i]  # λ v
    print(np.allclose(left, right))  # Should be True


True
True
True


In [126]:
M = np.array([
    [1, 2],
    [-1, 3]
])
eigval, eigvec = np.linalg.eig(M)
print("Eigenvalues:\n", eigval)
print("Eigenvectors:\n", eigvec)

Eigenvalues:
 [2.+1.j 2.-1.j]
Eigenvectors:
 [[0.81649658+0.j         0.81649658-0.j        ]
 [0.40824829+0.40824829j 0.40824829-0.40824829j]]


In [127]:
M = np.array([
    [1, 3, 1],
    [2, 4, 2]
])
U, sigma, Vt = np.linalg.svd(M)
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(2, 2)
(2,)
(3, 3)


In [129]:
sigma

array([5.89660208, 0.47967068])

In [130]:
U @ U.T

array([[ 1.00000000e+00, -1.08094514e-16],
       [-1.08094514e-16,  1.00000000e+00]])

In [131]:
Vt @ Vt.T

array([[ 1.00000000e+00,  2.97804097e-17,  1.56730402e-17],
       [ 2.97804097e-17,  1.00000000e+00, -2.93975883e-17],
       [ 1.56730402e-17, -2.93975883e-17,  1.00000000e+00]])

In [133]:
U @ np.diag(sigma) @ Vt[:2, :]

array([[1., 3., 1.],
       [2., 4., 2.]])